/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 *TASK:
 *Individual LED Blinking:

Green LED: Blink on and off every 1 second.
Red LED: Blink on and off every 1 second.
Orange LED: Blink on and off every 1 second.
Combinations of LEDs:

Green + Orange: Both LEDs turn on together for 1 second, then turn off together for 1 second.
Green + Red: Both LEDs turn on together for 1 second, then turn off together for 1 second.
Red + Orange: Both LEDs turn on together for 1 second, then turn off together for 1 second.
Multi-LED Pattern:

Green + Orange + Red: All three LEDs turn on together for 2 seconds, then turn off together for 2 seconds.
Sequential LED Pattern:

Green → Red → Orange: Turn on each LED sequentially with 2-second intervals, and turn them off in the same sequence.

OUTPUT:https://drive.google.com/file/d/1Xkgdr6Qrk1kNWPLfx0GfCzxZELPTDIzh/view?usp=drive_link
 ******************************************************************************
 */
 
#include "stm32f407xx.h"
#include "gpio.h"
#include "systick.h"
#include "main.h"

// Define LED pins
#define LED_GREEN_PIN  12  // Green LED
#define LED_RED_PIN    14  // Red LED
#define LED_ORANGE_PIN 13  // Orange LED

void GPIO_Init(void) {
    // Enable peripheral clock for GPIOD
    GPIO_ClockControl(GPIOD, ENABLE); // Enable clock for GPIOD

    // Initialize GPIO pins for LEDs
    GPIO_Pin_Init(GPIOD, LED_GREEN_PIN, GPIO_MODE_GENERAL_PURPOSE_OUTPUT, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_SPEED_MEDIUM, GPIO_PULL_NO, GPIO_AF_NONE);
    GPIO_Pin_Init(GPIOD, LED_ORANGE_PIN, GPIO_MODE_GENERAL_PURPOSE_OUTPUT, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_SPEED_MEDIUM, GPIO_PULL_NO, GPIO_AF_NONE);
    GPIO_Pin_Init(GPIOD, LED_RED_PIN, GPIO_MODE_GENERAL_PURPOSE_OUTPUT, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_SPEED_MEDIUM, GPIO_PULL_NO, GPIO_AF_NONE);

    // Initialize SysTick with a 1 ms tick
    SysTick_Init(SystemCoreClock / 1000U);
}

int main(void) {
    GPIO_Init();

    while (1) {
        // Individual LED Blinking
        // Green LED - 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_SET);  // Turn on green LED
        SysTick_Delay(1000);                                        // Delay 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_RESET);// Turn off green LED
        SysTick_Delay(1000);                                        // Delay 1 second

        // Red LED - 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_SET);    // Turn on red LED
        SysTick_Delay(1000);                                        // Delay 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_RESET); // Turn off red LED
        SysTick_Delay(1000);                                        // Delay 1 second

        // Orange LED - 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_SET); // Turn on orange LED
        SysTick_Delay(1000);                                         // Delay 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_RESET);// Turn off orange LED
        SysTick_Delay(1000);                                         // Delay 1 second

        // Combination of LEDs
        // Green + Orange - 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_SET);  // Turn on green LED
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_SET); // Turn on orange LED
        SysTick_Delay(1000);                                        // Delay 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_RESET);// Turn off green LED
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_RESET);// Turn off orange LED
        SysTick_Delay(1000);                                        // Delay 1 second

        // Green + Red - 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_SET);  // Turn on green LED
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_SET);    // Turn on red LED
        SysTick_Delay(1000);                                        // Delay 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_RESET);// Turn off green LED
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_RESET); // Turn off red LED
        SysTick_Delay(1000);                                        // Delay 1 second

        // Red + Orange - 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_SET);    // Turn on red LED
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_SET); // Turn on orange LED
        SysTick_Delay(1000);                                        // Delay 1 second
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_RESET); // Turn off red LED
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_RESET); // Turn off orange LED
        SysTick_Delay(1000);                                        // Delay 1 second

        // Multi-LED Pattern
        // Green + Orange + Red - 2 seconds
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_SET);  // Turn on green LED
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_SET); // Turn on orange LED
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_SET);    // Turn on red LED
        SysTick_Delay(2000);                                        // Delay 2 seconds
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_RESET);// Turn off green LED
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_RESET);// Turn off orange LED
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_RESET); // Turn off red LED
        SysTick_Delay(2000);                                        // Delay 2 seconds

        // Sequential LED Pattern
        // Green → Red → Orange - 2 second each
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_SET);  // Turn on green LED
        SysTick_Delay(2000);                                        // Delay 2 seconds
        GPIO_WriteToOutputPin(GPIOD, LED_GREEN_PIN, GPIO_PIN_RESET);// Turn off green LED
        SysTick_Delay(2000);                                        // Delay 2 seconds

        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_SET);    // Turn on red LED
        SysTick_Delay(2000);                                        // Delay 2 seconds
        GPIO_WriteToOutputPin(GPIOD, LED_RED_PIN, GPIO_PIN_RESET); // Turn off red LED
        SysTick_Delay(2000);                                        // Delay 2 seconds

        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_SET);// Turn on orange LED
        SysTick_Delay(2000);                                        // Delay 2 seconds
        GPIO_WriteToOutputPin(GPIOD, LED_ORANGE_PIN, GPIO_PIN_RESET);// Turn off orange LED
        SysTick_Delay(2000);                                        // Delay 2 seconds
    }
}
